services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
      - storage
    environment:
      - STORAGE_URL=http://storage:8080
      - SERVICE2_URL=http://service2:9090
    volumes:
      - ./vstorage:/vstorage

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: service2
    depends_on:
      - storage
    environment:
      - STORAGE_HOST=storage
      - STORAGE_PORT=8080
    volumes:
      - ./vstorage:/vstorage

  storage:
    build: ./storage
    container_name: storage
    volumes:
      - storage_data:/data
volumes:
  vstorage:
    driver: local
  storage_data: